6_Django-URLs-Templates/proj_UrlsTemplates/app_UrlsTemplates/urls.py
#URLs App: "app_UrlsTemplates"
'''
Archivo para declarar las URLs utilizadas dentro de la aplicación "app_UrlsTemplates"
'''
from django.urls import path
from app_UrlsTemplates import views

#Template Tagging
app_name = 'app_UrlsTemplates'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

6_Django-URLs-Templates/proj_UrlsTemplates/proj_UrlsTemplates/urls.py
from django.contrib import admin
from django.urls import path,include
from app_UrlsTemplates import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('app_UrlsTemplates/', include('app_UrlsTemplates.urls')),

]

6_Django-URLs-Templates/proj_UrlsTemplates/app_UrlsTemplates/models.py
from django.db import models

# Create your models here.

6_Django-URLs-Templates/proj_UrlsTemplates/app_UrlsTemplates/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    context_dict = {'text': 'hola mundo', 'number': 100}
    
    return render(request, 'app_UrlsTemplates/index.html', context_dict)

def other(request):
    
    return render(request, 'app_UrlsTemplates/other.html')

def relative(request):
    
    return render(request, 'app_UrlsTemplates/urls-templates.html')

6_Django-URLs-Templates/proj_UrlsTemplates/app_UrlsTemplates/templates/app_UrlsTemplates/base.html
<!DOCTYPE html>
{% load static %}<!--Línea para cargar contenido estático dentro del Proyecto-->

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Base</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="navbar-nav">
              <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
              <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
              <a class="nav-item nav-link" href="{% url 'app_UrlsTemplates:other' %}">Otro</a>
            </div>
          </nav>
        
          <div class="container">
            {% block body_block %}
            <!--Cualquier elemento fuera de esta equitqueta, será heredado si se extiende!-->
            {% endblock %}
        </div>
        <script src="" async defer></script>
    </body>
</html>

6_Django-URLs-Templates/proj_UrlsTemplates/app_UrlsTemplates/templates/app_UrlsTemplates/index.html
<!DOCTYPE html>
{% extends "app_UrlsTemplates/base.html" %}
    {% block body_block %}
        <div class="container">
            <div class="jumbotron">
                <h1>Página Home</h1>
                <h2>Este es el archivo index.html </h2><br>
                <!--<h3>{{ text |upper }}</h3> <!--|upper=filtro -->
                <h3>{{ text |cut:'mundo' }}</h3> <!--|cut=filtro customizado -->
                <h3>{{ number|add:"99" }}</h3> <!--|add:"99"=filtro -->
            </div>
        </div>
    {% endblock %}

6_Django-URLs-Templates/proj_UrlsTemplates/app_UrlsTemplates/templates/app_UrlsTemplates/other.html
<!DOCTYPE html>
{% extends "app_UrlsTemplates/base.html" %}
    {% block body_block %}
        <div class="container">
            <div class="jumbotron">
                <h1>Página Other</h1>
                <h2>Este es un ejemplo de Herencia de Templates</h2>
            </div>
        </div>
    {% endblock %}
            

6_Django-URLs-Templates/proj_UrlsTemplates/app_UrlsTemplates/templates/app_UrlsTemplates/urls-templates.html
<!DOCTYPE html>
{% load static %}<!--Línea para cargar contenido estático dentro del Proyecto-->

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Urls-Templates</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="jumbotron">
                <h1>Página Urls-Templates</h1>
                <a href="{% url 'app_UrlsTemplates:other' %}">La página "other".</a><br>
                <a href="{% url 'admin:index' %}">Link a Administrador.</a><br>
                <a href="{% url 'index' %}">Link a Index.</a>

            </div>
        </div>

        <script src="" async defer></script>
    </body>
</html>